### ISSUE TITLE
lost /data folder in harbor-core

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#360] opened 2020-12-21 04:48 UTC
2020-12-21T04:45:30Z [WARNING] [/core/systeminfo/imagestorage/filesystem/driver.go:51]: The path /data is not found, will return zero value of capacity

**Comment by heww** [comment] 2021-01-12 01:27
In the k8s cluster, the `/data` directory does not exist in the core component. The `/data` directory only exists in docker-compose mode. This is by design so I will close this issue.

**Closed by heww** 2021-01-12 01:27 UTC
Labels: area/harbor-components, kind/bug, priority/medium, release/1.0
